### ISSUE TITLE
I need some help from my fellow Balboa Owners. 

### ISSUE THREAD

**Issue by tonyfitzs** [plmilord/Hass.io-custom-component-spaclient#11]
Hi there, 

I am reaching out the my fellow Balboa Spa controller owners because I need some help with something. This is not directly related to the BWA client. Its more about the controller its self. 
A few days ago one of the pumps in my spa took a power spike that fused the motor. This also caused a huge current spike that resulted in an arc at the point where the power goes into the controller. 

I’m confident the controller is still able to be repaired, one thing that is great about the Balboa controller is they are almost bullet proof. Mind you I have never tried to shoot it, although I have been tempted. 

Anyway, I have a Balboa Revolution controller (BP1600) and I need to either get a copy of a circuit diagram or else just a picture of the board where the neutral power goes into the controller. I have attached a couple of photos of what I am talking about, I need to know if the neutral line or the active line connects to U11, as you can imaging this is a very significant difference. 

Thanks in advance, and sorry for the off-topic request, but I have run out of other options.

![20211111_161918](https://user-images.githubusercontent.com/34207637/141382139-bcfbd3ad-60c7-4415-afd5-3ab516d94ac4.jpg)
![20211111_161923](https://user-images.githubusercontent.com/34207637/141382147-680621e1-1f34-4c5f-abc1-1897a4f92789.jpg)

**Comment by plmilord** [comment]
I can't help on this one.  My spa ctrl doesn't look like this!

**Comment by tonyfitzs** [comment]
Ok thanks anyway.

**Comment by ric866** [comment]
Hi Both,

Firstly Pierre, I am most grateful for your work with the BWA WiFi module. It's nice to have such a problematic device under at least some kind of monitoring!

Tony, I'm not a qualified person (just to put that out there), but I've spent more time than I wanted looking inside hot tubs. 
You might find this useful : [BWG Service Manual](https://www.balboawatergroup.com/getdoc.cfm?id=1611) 
Page 27 on the right shows that link, and by the looks of it, it goes past the bottom terminal, to the middle one.

Hope that helps (even if a little). 

Kind regards

Ric

**Comment by tonyfitzs** [comment]
Thanks Ric,

This is very helpful.

**Comment by enkrypt3d** [comment]
Tony it may just be easier to buy the BP7 spa pack and start fresh... it's not too expensive.

**Comment by plmilord** [comment]
Sounds it has been answered by @ ric 866 ... I close this issue! Thanks for this great teamwork!
