### ISSUE TITLE
How to show temp graph?

### ISSUE THREAD

**Issue by enkrypt3d** [plmilord/Hass.io-custom-component-spaclient#13]
![image](https://user-images.githubusercontent.com/93238214/143478107-5ba08ded-3325-4e93-a74f-9f8a07a410e5.png)

I got this working as I had to reinstall my raspberry pi after a disk failure but now I'm not able to show the temp history when the heater runs? any ideas? I want to show how often the heater runs... it used to show an orange graph here but what entity is that?

**Comment by enkrypt3d** [comment]
disregard it just took some time to start working again!

**Comment by plmilord** [comment]
Okay, I close this issue!
