### ISSUE TITLE
Entity binary_sensor.filter_cycle_2_status implements device_state_attributes. Please report it to the custom component author

### ISSUE THREAD

**Issue by B-Hartley** [plmilord/Hass.io-custom-component-spaclient#15]
Entity binary_sensor.filter_cycle_2_status (<class 'custom_components.spaclient.binary_sensor.FilterCycle'>) implements device_state_attributes. Please report it to the custom component author.

Recent Home Assistant updates, need device_state_attributes updating to extra_state_attributes

https://developers.home-assistant.io/docs/core/entity/?_highlight=extra_state_attributes#generic-properties

**Comment by plmilord** [comment]
Thanks for the hint! Please refer to Spa Client version 2.3 now!

I fixed the device_state_attributes warning there and a few other little things...

**Comment by B-Hartley** [comment]
great, thanks !
