### ISSUE TITLE
Spa constantly showing circulating ?

### ISSUE THREAD

**Issue by B-Hartley** [plmilord/Hass.io-custom-component-spaclient#18]
Hi,

Not sure when this changed, feels like 2-3 weeks ago.
My spa is showing in home assistant as always circulating.
The circulation pump appears to be constantly on.
It isn't constantly on, it's just how it's showing up in the integration.

Is there any debug I can take a look at to understand what's happening ?

Thanks

**Comment by plmilord** [comment]
hmmm i'll take a look. In my last release, I played around with this code to "standardize" the code! I will come back to you as soon as I can... Thank-you for this sharing!

**Comment by plmilord** [comment]
To fix the circulation pump display issue, could you replace the `spaclient.py` file with this one: [spaclient.zip](https://github.com/plmilord/Hass.io-custom-component-spaclient/files/8120285/spaclient.zip)

Restart your Home Assistant -or- Reload the component and let me know if this work for you!

**Comment by B-Hartley** [comment]
That seems to have fixed it, thanks very much !
