### ISSUE TITLE
Detected integration that uses temperature utility - HA system log msg

### ISSUE THREAD

**Issue by berkavil** [plmilord/Hass.io-custom-component-spaclient#25]
Hallo plmilord, and thank you for this marvelous integration.

I would like to ask you - couple months ago I started to receive this warning in HA logs:

---
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 20:42:39 (2 occurrences)
Last logged: 20:42:39

Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for spaclient using this method at custom_components/spaclient/climate.py, line 105: return convert_temperature(self._spaclient.get_high_range_min(), TEMP_FAHRENHEIT, self.temperature_unit)
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for spaclient using this method at custom_components/spaclient/climate.py, line 112: return convert_temperature(self._spaclient.get_high_range_max(), TEMP_FAHRENHEIT, self.temperature_unit)
---

I guess you are aware of it, but I can't find anywhere in the docs - or issues list, if it is considered to be updated/repaired within the next update of this integration.

Thank you indeed for info.
W.

**Comment by plmilord** [comment]
Install the latest v2.6a and it should be fixed!
