### ISSUE TITLE
Wi-Fi Module compatibility 

### ISSUE THREAD

**Issue by jameshiscott** [plmilord/Hass.io-custom-component-spaclient#3]
Hi, thanks for your work on this HA module, do you know if this can connect with any Balboa system. I currently just have a dumb control box but want to be able to run the system when we have excess solar generation.

**Comment by plmilord** [comment]
Hi @jameshiscott,

By their documentation, Balboa seems to limit the use of that BWA module to those spa systems:

> BP501/601

> BP2000/2100/6013

> BP100/200

You'll find more info there: http://www.balboawatergroup.com/bwaios
