### ISSUE TITLE
Set pump speed in a script

### ISSUE THREAD

**Issue by lowema** [plmilord/Hass.io-custom-component-spaclient#35]
Hi there,
First, thank you for taking on this spa integration, it's great so far !
I'd dearly like to be able to set the pumps to full speed in a script or automation if possible

Is this possible, or can it be added as a new feature please ?

Thanks so much !

**Comment by plmilord** [comment]
I don't think to integrate this upgrade through this custom component. If you develop a script to do this, feel free to share it via the discussions available on this project.
