### ISSUE TITLE
Upgrade to 2.81 creates a new unit with new entities

### ISSUE THREAD

**Issue by markuswesterberg** [plmilord/Hass.io-custom-component-spaclient#45]
This upgrade needs to be revised. When upgrading it creates a second, duplicate unit with new entities named "....._2" and the original unit becomes unavailable.

**Comment by Jieper001** [comment]
I can confirm the same thing happened to me.  Not a major issue though.

**Comment by plmilord** [comment]
What version did you upgrade from? It's as if you were using a version older than 2.8. As noted in the 2.8 version notes, you need to uninstall the old version and reinstall this new one.

No _2 here...:

![image](https://github.com/plmilord/Hass.io-custom-component-spaclient/assets/46912935/d3036fd5-9ad9-4526-a017-d8eab3ce652a)

**Comment by markuswesterberg** [comment]
Ah! OK. My bad, I did upgrade from an older version. Will restore back-up and read the notes before upgrading, thanks!!

**Comment by plmilord** [comment]
Make sure to uninstall everything from Spa Client first, reboot, then install the latest version... this should be back under control for you!
