### ISSUE TITLE
implements HVACMode(s): heat, off  and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature

### ISSUE THREAD

**Issue by B-Hartley** [plmilord/Hass.io-custom-component-spaclient#46]
(<class 'custom_components.spaclient.climate.SpaThermostat'>) implements HVACMode(s): heat, off 
and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. 

Core: 2024.2.1
Supervisor: 2024.01.1
OS: 11.5

**Comment by B-Hartley** [comment]
https://developers.home-assistant.io/blog/2024/01/24/climate-climateentityfeatures-expanded/

**Comment by plmilord** [comment]
Version [v2.82](https://github.com/plmilord/Hass.io-custom-component-spaclient/releases/tag/v2.82) eliminates this warning message.

Thx.
