### ISSUE TITLE
Der Konfigurationsfluss konnte nicht geladen werden: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by Mart-Muc** [plmilord/Hass.io-custom-component-spaclient#48]
Hallo,

habe gerade das HACS Modul installiert,
2x neustart und nun will ich die Integration hinzufügen.

leider kommt nur diese Fehlermeldung.... was tun??

PS: Balboa BP6013G2 mit WIFI-Modul, lokaler Zugriff der "Spa Control" app auf dem iphone funktioniert.

Danke, Mart

**Comment by plmilord** [comment]
Hallo Mart, ich werde mein bestes Deutsch versuchen (lang lebe Google Translate)!

Sie müssen verstehen, dass das Modul „bwa“ jeweils nur eine Verbindung akzeptiert. Bitte schließen Sie die App auf Ihrem Mobiltelefon vollständig, bevor Sie Spaclient auf HomeAssistant installieren.

Kontaktieren Sie mich erneut, um zu sehen, ob Ihr Problem dadurch behoben wird.

Pierre-Luc
