### ISSUE TITLE
Error with support ending in 2025.3

### ISSUE THREAD

**Issue by monsieurlatte** [plmilord/Hass.io-custom-component-spaclient#52]
Clearly no rush on this just a heads up I'm sure you're aware of :) 

Logger: homeassistant.components.light
Source: components/light/__init__.py:1267
integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 11:50:44 AM (1 occurrences)
Last logged: 11:50:44 AM

None (<class 'custom_components.spaclient.light.SpaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-spaclient/issues

**Comment by plmilord** [comment]
Thanks for pointing this out to me... [Spa Client v3.0](https://github.com/plmilord/Hass.io-custom-component-spaclient/releases/tag/v3.0) takes care of this warning now!

PL
