### ISSUE TITLE
Conflict between HA app and BWA mobile app

### ISSUE THREAD

**Issue by javo222** [plmilord/Hass.io-custom-component-spaclient#53]
Hi,
I have the Balboa Android app and it works fine, but as soon as I enable the spaclient in HA, I can no longer to the spa in the app. It gets stuck on a loading screen saying "Synching with SPA 52E242"...

Even after disabling the spaclient and restarting my SPA, I cannot connect. I have to reset my Wifi module to get it to work in the Balboa app again.

Any idea why there is such a conflict?
Thanks
Firmware: M100_226 V34.0

**Comment by plmilord** [comment]
The Balboa module can only support one local connection... if you still want to use the Balboa app on your phone while using this custom component, you must use the Cloud Connect option when opening the Balboa app.

**Comment by javo222** [comment]
I thought I tried that but after reading your message I tried again and it worked. Thank you!
