### ISSUE TITLE
SpaLight - does not set supported color modes - issue

### ISSUE THREAD

**Issue by berkavil** [plmilord/Hass.io-custom-component-spaclient#58]
Hallo, after the last core update this error msg. started to apear:

Logger: homeassistant.components.light
Zdroj: components/light/__init__.py:1276
---
None (<class 'custom_components.spaclient.light.SpaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/plmilord/Hass.io-custom-component-spaclient/issues

so far it seems to be working, only I see this warning msg in the log.
thx.

**Comment by plmilord** [comment]
This issue has been resolved since Spa Client version 3.0... The latest release is now [v3.2](https://github.com/plmilord/Hass.io-custom-component-spaclient/releases/tag/v3.2)
