### ISSUE TITLE
SpaThermostat implements HVACModes and therefore implicitly supports the turn_on/turn_off - issue

### ISSUE THREAD

**Issue by berkavil** [plmilord/Hass.io-custom-component-spaclient#59]
Hallo, since the last HA core update I started to receive this msg. in the system log.(so far all seems to be working as usual, but maybe I just don't use these functions...

---
Logger: homeassistant.components.climate
Zdroj: components/climate/__init__.py:370

Entity None (<class 'custom_components.spaclient.climate.SpaThermostat'>) implements HVACMode(s): heat, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/plmilord/Hass.io-custom-component-spaclient/issues

**Comment by plmilord** [comment]
Same... Please update to the latest release [v3.2](https://github.com/plmilord/Hass.io-custom-component-spaclient/releases/tag/v3.2)
