### ISSUE TITLE
Light not showing in home assistant

### ISSUE THREAD

**Issue by B-Hartley** [plmilord/Hass.io-custom-component-spaclient#6]
Hi,

I've been using.......
https://github.com/garbled1/balboa_homeassistan

But recently found your component, so I'm giving it a go.
My lights have not appeared in your component, but they did in the other one.
Is there anything I can do to make them work? or to help you get them to work?

Thanks,
Bruce.

**Comment by plmilord** [comment]
It looks weird...

Could you copy and paste the `<< Configuration variables >>` section found in your `home-assistant.log`?

Have you tried reinstalling the custom component?

**Comment by B-Hartley** [comment]
I did a home assistant restart and it appeared. 

Thanks.

**Comment by B-Hartley** [comment]
I notice your component displays decimal temps such as 36.9
The previous one and the tub itself only shows .5 degrees. 
Are you provided with accurate temps or is it some kind of unit conversion issue ?
